row_detection:
  ros__parameters:
    use_sim_time: false
    y_max_threshold: 1.5       # y max threshold to include points in clustering
    y_min_threshold: 0.5       # y min threshold to include points in clustering
    x_threshold: 4.0       # x threshold to include points in clustering
    use_weighting: False   # use trapezoid function to weight x value of points
    alpha: 0.2             # alpha parameter for L1 Lasso regression
    min_pts_row: 2      # min number of points in a row to consider line fitting
    x_pred: 10.0        # x value to feed to predict line fit
    desired_x: 1.5      # x value of desired goal pose 
    pose_pub_topic: "/goal_pose"
    cluster_sub_topic: "/row_detection_processor_xyz/euclidean_cluster_extraction/clusters"
    detection_status_topic: "/in_row_flag"

row_exit_detection:
  ros__parameters:
    y_max_threshold_exit: 2.5      # y max threshold to include points in clustering
    cluster_sub_topic: "/row_detection_processor_xyz/euclidean_cluster_extraction/clusters"
    detection_status_topic: "/exit_det_flag"

row_detection_processor_xyz:
  ros__parameters:
    use_sim_time: false
    input_topic: "/points"
    processor_plugins: [
        "crop_box",
        "voxel_grid",
        "robot_crop_box",
        "radius_outlier_removal",
        "ground_plane_fitting",
        "euclidean_cluster_extraction",
      ]

    crop_box:
      plugin: "pcl_processor::CropBox"
      min: [-10.0, -10.0, -10.0]
      max: [10.0, 10.0, 10.0]
      negative: false

    voxel_grid:
      plugin: "pcl_processor::VoxelGrid"
      leaf_size: [0.1, 0.1, 0.1]
      downsample_all_data: true
      min_points_per_voxel: 0
      save_leaf_layout: false

    # Remove points on robot
    robot_crop_box:
      plugin: "pcl_processor::CropBox"
      min: [-0.9, -0.35, -1.0]
      max: [0.15, 0.35, 1.0]
      negative: true

    radius_outlier_removal:
      plugin: "pcl_processor::RadiusOutlierRemoval"
      radius_search: 0.25
      min_points_per_voxel: 5
      

    euclidean_cluster_extraction:
      plugin: "pcl_processor::EuclideanClusterExtraction"
      cluster_tolerance: 0.25
      min_cluster_size: 20
      max_cluster_size: 600
      publish_markers: true

    ground_plane_fitting:
      plugin: "pcl_processor::GroundPlaneFitting"
      num_iterations: 10
      num_lpr: 20
      initial_seeds_threshold: 1.0
      plane_dist_threshold: 0.25
      negative: true

